// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZvc4kYit5OWMH4q61JgGznlDEL11xx0s',
    appId: '1:191438346378:web:96881f94ffbb6d6d15b573',
    messagingSenderId: '191438346378',
    projectId: 'trab-fernando',
    authDomain: 'trab-fernando.firebaseapp.com',
    storageBucket: 'trab-fernando.appspot.com',
    measurementId: 'G-MV3EVKVKDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-08Mf9gXNZoWWI9tj_f5Ab9vkCi5084',
    appId: '1:191438346378:android:902e549ab51549b515b573',
    messagingSenderId: '191438346378',
    projectId: 'trab-fernando',
    storageBucket: 'trab-fernando.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhhNHLTUMjGjWnDd8J3-pMdifkVENfBA',
    appId: '1:191438346378:ios:829c799e97db35b215b573',
    messagingSenderId: '191438346378',
    projectId: 'trab-fernando',
    storageBucket: 'trab-fernando.appspot.com',
    iosBundleId: 'com.example.flutterTrabalho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhhNHLTUMjGjWnDd8J3-pMdifkVENfBA',
    appId: '1:191438346378:ios:2bbbd3a8bb548dcb15b573',
    messagingSenderId: '191438346378',
    projectId: 'trab-fernando',
    storageBucket: 'trab-fernando.appspot.com',
    iosBundleId: 'com.example.flutterTrabalho.RunnerTests',
  );
}
